main:
- identifier: menu1
  name: Menu 1
  title: Mon menu 1
  url: /menu1/
  weight: 1
- identifier: menu1.2
  name: Menu1.2
  title: Mon menu 1.2
  url: /menu1/menu1.2
  weight: 2
  parent: menu1
- identifier: menu1.1
  name: Menu 1.1
  title: Mon menu 1.1
  url: /menu1/menu1.1
  weight: 1
  parent: menu1
- identifier: menu2
  name:  Menu 2
  title: Mon menu 2
  url: /menu2/
  weight: 1
- identifier: menu3
  name:  Menu 3
  title: Mon menu 3
  url: /menu3/
  weight: 1

footer:
- identifier: plan_site
  name: Plan du Site
  url: /plan-site/
  weight: 1
- identifier: accessibilite
  name: "Accessibilité: non/partiellement/totatelement conforme"
  url: /accessibilite/
  weight: 2
- identifier: mentions_legales
  name: Mentions légales
  url: /mentions-legales/
  weight: 3
- name : Données personnelles
  url: /donnees-personnelles/
  weight: 4
- identifier: gestion_cookies
  name: Gestion des cookies
  url: /gestion-cookies/
  weight: 5
