theme: "hugo-design-gouv"
baseURL: http://example.org/
languageCode: en-us
title: Quel beau titre
params:
  header:
    bloc_marque: Préfet $de la Seine-$Maritime
    url: /
    logo:
      url: /img/speric.png
      alt: logo Speric
    service: 
      title: DDTM 76
      tagline: Direction départementale des territoires<br> et de la mer de Seine-Maritime
    search: true
  footer:
    bloc_marque: Préfet $de la Seine-$Maritime
  theme:
    style: light
    switch_theme_position: none

menu:
  main:
  - identifier: menu1
    name: Menu 1
    title: Mon menu 1
    url: /menu1/
    weight: 1
  - identifier: menu1.2
    name: Menu1.2
    title: Mon menu 1.2
    url: /menu1/menu1.2
    weight: 2
    parent: menu1
  - identifier: menu1.1
    name: Menu 1.1
    title: Mon menu 1.1
    url: /menu1/menu1.1
    weight: 1
    parent: menu1
  - identifier: menu2
    name:  Menu 2
    title: Mon menu 2
    url: /menu2/
    weight: 1

markup:
  goldmark:
    renderer:
      unsafe: true
